#!/usr/bin/env python3
"""Steamworks Partner Account integration scaffolding for Shadow Garden.

This module provides:
  - Checklist for Steamworks Partner account setup
  - Configuration templates for base + adult DLC depots
  - Readiness status checker
  - Integration hooks for shadow_garden_packet

Note: Actual Steamworks authentication and API calls require separate credentials.
This module is content-neutral scaffolding only.

Usage:
    python3 steamworks_integration.py checklist
    python3 steamworks_integration.py readiness
    python3 steamworks_integration.py config-template
    python3 steamworks_integration.py self-test
"""

from __future__ import annotations

import json
import os
from typing import Any


STEAMWORKS_SETUP_STEPS = [
    {
        "step": 1,
        "title": "Create Steamworks Partner Account",
        "description": "Set up a separate partner account (not personal account)",
        "url": "https://partner.steampowered.com/",
        "notes": "Requires legal entity information, tax interview (W-9/W-8), payout bank account",
    },
    {
        "step": 2,
        "title": "Pay $100 App Deposit",
        "description": "Submit app deposit per title to Steamworks",
        "notes": "Non-refundable; covers administrative costs",
    },
    {
        "step": 3,
        "title": "Create Base Game Depot",
        "description": "Set up depot for core game content (no adult material)",
        "config": {
            "depot_id": "<auto-generated>",
            "name": "Shadow Garden Base",
            "description": "Core game content (story, mechanics, non-adult features)",
            "content_restrictions": ["no_sexual_content", "no_adult_themes"],
        },
    },
    {
        "step": 4,
        "title": "Create Adult DLC Depot (Separate)",
        "description": "Set up separate depot for adult-only sexual content",
        "config": {
            "depot_id": "<auto-generated>",
            "name": "Shadow Garden - Adult DLC",
            "description": "Adult-only sexual content DLC",
            "age_gate": "18+",
            "content_flags": ["sexual_content"],
            "parent_app_id": "<base_game_app_id>",
        },
        "notes": "MUST be separate depot; no single flag unlock in base build",
    },
    {
        "step": 5,
        "title": "Declare Adult Content",
        "description": "Mark app as containing sexual content in Steamworks",
        "notes": "Triggers age-gated store page; customers aged 18+ only see it",
    },
    {
        "step": 6,
        "title": "Submit to Valve Review",
        "description": "Submit base game for content review",
        "notes": "Review takes ~5 business days; adult DLC requires additional review",
    },
]

STEAMWORKS_CONFIG_TEMPLATE = {
    "schema": "shadow_garden.steamworks_config.v1",
    "app_id": "<get_from_steamworks_partner>",
    "organization": {
        "legal_name": "<your_legal_entity>",
        "partner_account_id": "<not_personal_account>",
    },
    "base_game": {
        "depot_id": "<auto>",
        "name": "Shadow Garden",
        "description": "The core Shadow Garden experience",
        "build_output": "<path_to_build>",
        "content_restrictions": ["no_sexual_content"],
    },
    "dlc_adult": {
        "depot_id": "<auto>",
        "name": "Shadow Garden - Adult DLC",
        "description": "Adult-only sexual content",
        "parent_app_id": "<base_game_app_id>",
        "build_output": "<path_to_adult_build>",
        "age_gate": "18+",
        "content_flags": ["sexual_content"],
        "payment_processor_policy": "Visa/Mastercard require separate depot for adult content",
    },
    "publishing": {
        "base_game_page_type": "game",
        "dlc_page_type": "addon",
        "dlc_page_visibility": "age_gated_18_plus",
        "refund_policy": "Within 14 days, under 2 hours played",
    },
}


def get_checklist() -> dict[str, Any]:
    """Return the full Steamworks setup checklist."""
    return {
        "schema": "shadow_garden.steamworks_checklist.v1",
        "status": "not_ready_pending_partner_account",
        "constraint": "payment_processor_policy_not_code",
        "explanation": "Visa/Mastercard require separate depots for adult sexual content; no code setting overrides this",
        "setup_steps": STEAMWORKS_SETUP_STEPS,
        "key_points": [
            "Use separate Steamworks Partner account (NOT personal account)",
            "Adult content MUST be in separate depot (enforced by payment processors)",
            "Base game is age-restricted from adult DLC; no single-flag unlock",
            "Age-gated store page automatically shown to 18+ only",
            "Review process: base game ~5 days, adult DLC ~10 days",
        ],
    }


def get_config_template() -> dict[str, Any]:
    """Return the Steamworks configuration template."""
    return STEAMWORKS_CONFIG_TEMPLATE


def check_readiness() -> dict[str, Any]:
    """Check if Steamworks setup prerequisites are met."""
    checks = {
        "partner_account_exists": os.getenv("STEAMWORKS_PARTNER_ID") is not None,
        "app_id_configured": os.getenv("STEAMWORKS_APP_ID") is not None,
        "base_build_path": os.getenv("STEAMWORKS_BASE_BUILD_PATH") is not None,
        "adult_build_path": os.getenv("STEAMWORKS_ADULT_BUILD_PATH") is not None,
    }

    ready = all(checks.values())

    return {
        "schema": "shadow_garden.steamworks_readiness.v1",
        "overall_ready": ready,
        "prerequisites": checks,
        "next_steps": [
            "1. Create separate Steamworks Partner account (https://partner.steampowered.com/)",
            "2. Complete tax interview and add payout bank account",
            "3. Pay $100 app deposit per title",
            "4. Export STEAMWORKS_PARTNER_ID, STEAMWORKS_APP_ID to environment",
            "5. Build base game and adult DLC separately",
            "6. Export STEAMWORKS_BASE_BUILD_PATH and STEAMWORKS_ADULT_BUILD_PATH",
            "7. Run: python3 steamworks_integration.py readiness",
        ] if not ready else ["✓ Steamworks prerequisites met; ready to submit"],
    }


def run_self_test() -> dict[str, Any]:
    """Verify the module functions work correctly."""
    checks = []

    checklist = get_checklist()
    if checklist.get("schema") == "shadow_garden.steamworks_checklist.v1":
        checks.append("checklist_generation")

    config = get_config_template()
    if config.get("schema") == "shadow_garden.steamworks_config.v1":
        checks.append("config_template_generation")

    readiness = check_readiness()
    if readiness.get("schema") == "shadow_garden.steamworks_readiness.v1":
        checks.append("readiness_check")

    return {"ok": True, "tests": len(checks), "checks": checks}


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Steamworks Partner Account integration scaffolding")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("checklist")
    sub.add_parser("config-template")
    sub.add_parser("readiness")
    sub.add_parser("self-test")

    args = parser.parse_args()

    if args.command == "checklist":
        result = get_checklist()
    elif args.command == "config-template":
        result = get_config_template()
    elif args.command == "readiness":
        result = check_readiness()
    elif args.command == "self-test":
        result = run_self_test()
    else:
        result = {"error": "unknown command"}

    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
